### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DukeNukem4ever** [DRRP-Team/DRRP#13]
![image](https://user-images.githubusercontent.com/31654733/56095172-ceffc800-5ee2-11e9-94b2-95a0879d4e9d.png)
I'm trying to launch the pk3 file with GZDoom, but I keep getting this mistake. And yes, the same thing happens with the latest version of the file.
What should I do?

**Comment by usernameak** [comment]
Update GZDoom.

**Comment by PROPHESSOR** [comment]
Use GZDoom 3.5.1+
