### ISSUE TITLE
'Always mouselook: off' breaks the camera

### ISSUE THREAD

**Issue by DevilDimon** [DRRP-Team/DRRP#32]
Preconditions:
- Set the setting 'Always mouselook' to off in Options - Mouse options
- Attack any enemy, crate or a broken door with any weapon

Expected behaviour:
- The camera remains in the same vertical position

Actual behaviour:
- The camera moves up (if you shoot a gun) or down (if you use the axe) and there's no way to get it back as vertical movement is disabled by the setting

Environment:
LZDoom 3.88b
macOS 12.3.1 (Intel)

**Comment by PROPHESSOR** [comment]
Please, use the option from DRRP Menu->Other

**Comment by PROPHESSOR** [comment]
Did it help?

**Comment by FaceHiddenInsideTheDark** [comment]
DRRP Menu -> Misc -> Disable freelook
Works 100% perfectly in latest master; tested with Axe, Shotgun, and Pistol.

Though, it does make it impossible to see the labels of objects like table, crate, sm medkit, ect, even if actors are set as infinitely tall.
